version: '3.7'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - JWT_SECRET_KEY=kzGLrfIQsp0d$823f5b562a681be74b11723b3943a492692i
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
